
#include "mapper/vrc.cpp"

#include "mapper/0.cpp"
#include "mapper/1.cpp"
#include "mapper/2.cpp"
#include "mapper/3.cpp"
#include "mapper/4.cpp"
#include "mapper/5.cpp"
#include "mapper/7.cpp"
#include "mapper/9.cpp"
#include "mapper/10.cpp"
#include "mapper/23.cpp"
#include "mapper/24.cpp"
#include "mapper/69.cpp"
